- cmd/root.go
When running on CircleCI, the default path is not a standard golang
format, so infering the organisation and project from the path
doesn't work correctly.
While we could explicitly set the organisation and project via flags,
using the circleci supplied env vars to grab the values produces
a cleaner circle.yml
commit 16a719b118ae49cf535c61a69de4bcf082301d3b
> Adds support for fetching org and project from circleci env vars

- cmd/deploy.go
- utils/kubernetes.go
When running in circle, we currently provide kubernetes
certificates via env vars.
This changeset lets us automatically fetch them,
which makes the circle.yml simpler
> Adds support for fetching kubernetes certificates from environment

- cmd/build.go
The kubernetes clients use `/x/text/`, which uses cgo.
This changeset links c code statically, so the entire binary is
entirely linked statically
> Modifies build to statically link cgo code

- cmd/deploy.go
Towards https://github.com/giantswarm/architect/issues/19
The email flag is deprecated in docker, so this changeset
removes it.
> Removes docker email from docker login

- commands/commands.go
- commands/commands_test.go
Towards https://github.com/giantswarm/architect/issues/16
This changeset adds support for detecting passwords in
task name output, and automatically redacting them.
e.g;
```
2017/03/04 16:12:41 running command: docker-login: 'docker login --email=circleci@giantswarm.io --username=circleci --password=[REDACTED] registry.giantswarm.io'
```
> Redacts passwords in output

- cmd/deploy.go
- workflow/workflow.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1300
This provides no new functionality, but prepares the `workflow` package for deploying to multiple clusters (with clusters being an array, instead of a set of strings)
Splitting it up into 2 PRs because this one is already pretty chunky, and I can see wiring the frontend being messy too - I'll do that next.
> Adds support to workflow package to deploy to multiple clusters

- utils/glide.go
- utils/glide_test.go
- workflow/workflow.go
Towards https://github.com/giantswarm/architect/issues/4
I found a subtle bug where a package containing no golang files, but containing a directory with golang files in, was not correctly listed as a package to test. This is fixed now.
> Adds tests, refactors novendor

- utils/glide.go
- utils/glide_test.go
Golang considers directories that begin with an underscore to
not be packages. This behaviour is also present in glide.
This changeset brings the behaviour of architect up to match
glide, by ignoring directories starting with underscores.
See: https://golang.org/pkg/go/build/#Context.Import
> Adds support for ignoring directories starting with underscore

- installation/aws.go
We're serving Vault behind an ELB, which handles on 443.
> Removes unnecessary port from vault address

- configuration/giantswarm/desmotes/desmotes.go
- configuration/giantswarm/giantswarm.go
- configuration/giantswarm/passage/passage.go
- installation/aws.go
- installation/leaseweb.go
We'll need this config per installation. It does make me want to move stuff that passage does more into API, as well as Desmotes. or at least put Passage and Desmotes 'behind' API.
But for now we'd need it. @JosephSalisbury what do you think?
> Add config for services that Happa relies on

- configuration/giantswarm/giantswarm.go
- configuration/giantswarm/happa/happa.go
- installation/aws.go
- installation/leaseweb.go
Similar to https://github.com/giantswarm/architect/pull/49, but now for Happa itself.
Happa's ingress manifest needs to know what domain Happa is on, as does desmotes for proper CORS configuration. 
This then also seems the right place to tell Happa what type of cluster creation form to show the user (the aws or the kvm version).
Once https://github.com/giantswarm/architect/pull/49 is approved and merged, I'll change the base of this PR to `master`
> Add config structures for Happa

- installation/aws.go
Towards https://github.com/giantswarm/adidas/issues/47
EC2 instances are billed hourly, so a testbot interval of 5 minutes works out to running 12 extra clusters. 30 minutes is 2 clusters, and seems much more reasonable in terms of cost.
> Decreases testbot interval to thirty minutes

- workflow/workflow.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/architect/issues/46
We previously checked whether a file named `main.go` existed in
the project. This is not sufficient for libaries, which may not
have a file named `main.go`. This changeset changes the check
for a file with a `.go` suffix, so that libraries will be built.
> Changes golang check to file with .go file extension

- installation/aws.go
Add a few more instance types to the list of allowed instance types for our AWS installations so we can properly test this feature.
> Add more allowed instance types for the aws installation

- commands/commands.go
- commands/commands_test.go
- workflow/golang.go
In order to do some integration testing, it would be handy if the architect build could reach services that are started up on the host. 
That way we don't have to try and do something more complex like passing in links as part of `architect build`
> Network host

- circle.yml
- cmd/version.go
Don't exit with status code 1 if no version information available.
See https://github.com/giantswarm/architect/issues/83 for fixing the (now missing, due to building with architect) build information.
> Exits cleanly if no version information

- configuration/guest/guest.go
- configuration/guest/kubectl/kubectl.go
- installation/aws.go
- installation/leaseweb.go
With this PR, `architect` sets the version of the kubectl image.
I decided to create a separate package for `kubectl` config. Not sure if it makes more sense to have it within the `kubernetes` package.
Towards  https://github.com/giantswarm/k8scloudconfig/issues/136
> add kubectl config

- configuration/auth/vault/vault.go
- installation/aws.go
- installation/leaseweb.go
Towards giantswarm/giantswarm#1504
Until we have automated renewal of certs we want to make them valid for 6 months. This PR adds a Certificate block to Vault and sets both it and the token TTL to 6 months.
> Set certificate and token TTLs to 6 months

- configuration/provider/aws/aws.go
- configuration/provider/aws/route53/hostedzones/hostedzones.go
- configuration/provider/aws/route53/route53.go
- installation/aws.go
Towards giantswarm/giantswarm#1501
Adds Route53 section to the AWS provider and sets values for the hosted zones. This is because creating hosted zones should be part of installation setup.
> Adds Route 53 settings to AWS provider

- events/events.go
This should've been `viking` and not `vikings`
> Fix codename for viking installation

- configuration/guest/calico/calico.go
- configuration/guest/guest.go
- configuration/provider/kvm/flannel/flannel.go
- installation/leaseweb.go
changes to address customized networks for `kubernetesd` https://github.com/giantswarm/kubernetesd/pull/205 and https://github.com/giantswarm/installations/pull/5
> customizable-networks

- template/helm.go
- template/helm_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1655
We need to support templating values in files that include
Helm templating.
Moving to use square brackets for delimeters for the architect
templating means that we don't clobber the helm templating,
and that there's a better distinction between the templating phases.
> Changes architect templating to use square brackets for delim

- configuration/guest/guest.go
- configuration/guest/ingress/ingress_controller.go
Towards giantswarm/giantswarm#1695
This PR adds the version of the Ingress Controller docker image to the guest provider. This is so we use a retagged image and can replace the hardcoded image in `k8scloudconfig`.
> Add ingress controller version to the guest provider

- workflow/golang.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/2061
We were previously using a slightly hackish method for detecting
whether there were any golang files in the directory.
This changeset moves us to use a walk, which properly detects golang
files in a project with many nested directories.
> Changes to use proper walk for golang detection

- workflow/helm.go
- workflow/workflow.go
These changes add the just built chart to the `stable` channel on deploy, this will allow us to reference and use the charts currently deployed from CI setups.
In order to make unit tests happy the promotion to stable is only done when a dockerfile is in place. Also the promotion task is bound to the stable channel, imo we don't need to parameterize the channel, let me know wdyt.
> promote chart to stable channel on deploy

- template/helm.go
- template/helm_test.go
After the recent issues with go escaping `<` in our rules.
> Remove html template import

- workflow/error.go
- workflow/workflow.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1902
Prevents trying to push an empty string as channel name.
> do not push empty channels

- Gopkg.lock
- Gopkg.toml
- tasks/concurrent.go
- tasks/concurrent_test.go
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/errgroup/errgroup.go
- workflow/golang.go
- workflow/workflow.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/2711 and https://github.com/giantswarm/giantswarm/issues/2678
Adds a `ConcurrentTask` type that runs a set of tasks concurrently using `errgroup.Group`. Also introduces changes to run the Go tasks concurrently, this is compatible with the changes introduced in #203, if we want to reuse the cache from the build step we just need to remove the build task from the concurrent set and execute it in the first place. We can measure in which situation we can have more gains (run build and test sequentially and take advantage of build cache in test or run build and test concurrently without cache).
This concurrent task can be used in more workflows, if we agree on the approach I'll propose more changes next.
> Add concurrent tasks and run go tasks concurrently

- workflow/docker.go
- workflow/docker_test.go
- workflow/workflow.go
- workflow/workflow_test.go
Currently all the repos run `architect deploy` as part of the single `build` job, as in https://github.com/giantswarm/kvm-operator/blob/master/.circleci/config.yml#L16
When we introduced e2e tests in aws-operator this way of deploying was kept until we have fast and reliable tests; after merging to master we build, deploy, and then we run e2e tests. We aim to condition the deployment to the result of the e2e tests, and only deploy when we are confident that things are working.
For that we need to have a separate `deploy` job, as in https://github.com/giantswarm/chart-operator/blob/master/.circleci/config.yml first build, then e2e tests and then, if things went well, deploy. The problem is that the final deploy step is run in a machine different from the one that did the build, and the …
> Add docker pull task to deploy workflow

- workflow/golang.go
When something breaks it's difficult to realize what went wrong. Also circle elides long output.
> workflow: make go builds and tests less verbose

- github-release.sh
Closes https://github.com/giantswarm/architect/issues/195
Instead of showing the json response on upload we get the http status code and check for a 2xx, anything different from that will fail the build.
> Fail build on upload error

- workflow/helm.go
- workflow/workflow.go
- workflow/workflow_test.go
Currently only `<project-name>-chart` is being pushed to stable on deploy, to be able to install from channel additional charts in a helm directory we need to push to stable all of them.
> Enable push to stable for multiple charts

- cmd/unpublish.go
- workflow/helm.go
- workflow/workflow.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1902, https://github.com/giantswarm/giantswarm/issues/2706.
Add `architect unpublish` to cleanup channels on the CNR after pushing to temporary channels. This needed e.g. in guest cluster charts, where channels get created only for a specific CI helm test run.
> Add unpublish command

- workflow/golang.go
Closes https://github.com/giantswarm/architect/issues/123
```
$ wc -c ./api
19247544 ./api
$ wc -c ./api
13418280 ./api
```
`api` sees about 30% reduction in total binary size
```
$ wc -c ./aws-operator
81727136 ./aws-operator
$ wc -c ./aws-operator
55810232 ./aws-operator
```
Same for `aws-operator`
See https://golang.org/doc/gdb#Introduction for additional information.
> Adds support for stripping DWARF from binaries

- events/events.go
Modifies axolotl project list to add `route53-manager`, this is meant to be active only until route53 is available on AWS China.
> Add route53-manager to axolotl project list

- events/events.go
We don't use this anymore for a _while_ apparently.
> Remove jackel from deployment list

- cmd/build.go
We have a golang 1.10.4 image as of https://github.com/giantswarm/retagger/pull/138
> Upgrade default golang version to 1.10.4

- events/events.go
Towards: https://github.com/giantswarm/giantswarm/issues/4282
route53-manager installation fix is merged: https://github.com/giantswarm/route53-manager/pull/9
This reverts commit 46bc99f2e304b3fb43d6050f0ffe373dc085d9af. from: https://github.com/giantswarm/architect/pull/253
> Revert "remove-route53-from-girafe (#253)"

- workflow/golang.go
By vomiting nonsense output during go build...
> workflow: prevent circle waiting for output timeouts

- workflow/workflow.go
- workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/4417
Templating didn't get executed on `architect publish` command yet.
> Add templating to publish command

- tasks/docker_test.go
- workflow/golang.go
I don't want to waste time to figure out what's wrong with builds like https://circleci.com/gh/giantswarm/e2e-harness/2093?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Error is:
```
pkg/release/release.go:110:15: undefined: k8sClient
pkg/release/release.go:111:15: undefined: c
pkg/release/release.go:129:21: config.FileLogger undefined (type Config has no field or method FileLogger)
```
I spot it because I ran the test on my local machine w/o `-v` option.
And this is relatively small project.
JUnit report wasn't helpful. I think because:
```
2018/10/25 06:18:29 generating Junit report at: /tmp/results/golang/results.xml
2018/10/25 06:18:29 could not execute workflow: <nil>
```
> workflow: make go test quiet

- cmd/build.go
Towards: https://github.com/giantswarm/giantswarm/issues/4461
Note: after this PR is merged, we should all move to go 1.11 and reformat repos.
> update golang version to 1.11.1

- workflow/golang.go
* fix the CGO_ENABLED environment variable
* remove build tag netgo. Not necessary if CGO is disabled and default since 1.5 anyway.
* set linkmode to auto. External doesn't work in eg `retagger` or `ci-cleaner` projects. Failed with `loadinternal: cannot find runtime/cgo`. Internal discussion https://gigantic.slack.com/archives/C3C7ZQXC1/p1540656174012000
> fix go 1.11 builds

- tasks/docker.go
- tasks/docker_test.go
Not sure what the issue was about. The URL in the comment gives 404.
I found this snippet (from
https://circleci.com/docs/2.0/building-docker-images/):
- run: |
container will be killed after finish
docker run --name app app-image:1.2.3
It looks like they are now fine with using --rm.
> tasks: always remove docker containers

- DCO
- workflow/error.go
- workflow/repo.go
- workflow/workflow.go
- workflow/workflow_test.go
Closes https://github.com/giantswarm/giantswarm/issues/5029
This will apply to *all* repos that `architect` builds, but I think having a switch based on public/private isn't necessary - if we should do it for public repos, we should do it for private repos too.
> Fail builds if DCO or LICENSE files are missing

- events/events.go
Endpoint-operator is nowadays part of kvm-operator and not used as independent
operator. Therefore there's no point in following it by architect either.
> Remove endpoint-operator from kvmProjectList

- LICENSE
- workflow/error.go
- workflow/repo.go
Fixes https://github.com/giantswarm/giantswarm/issues/5094
Checks the text is correct based on https://github.com/giantswarm/example-opensource-repo/blob/5badb5cac85bf9a0177ec06c16e2ac42f63f7ac6/LICENSE#L189.
Output if the check fails.
```
2019/01/29 13:11:25 running task: repo-check
repo has required file 'DCO'
repo has required file 'LICENSE'
repo 'LICENSE' file does not contain required text 'Copyright 2016 - 2019 Giant Swarm GmbH'
```
Output if the check passes.
```
2019/01/29 13:13:09 running task: repo-check
repo has required file 'DCO'
repo has required file 'LICENSE'
repo 'LICENSE' has required text 'Copyright 2016 - 2019 Giant Swarm GmbH'
```
>  Add check for license text format

- workflow/golang.go
Towrads: https://github.com/giantswarm/giantswarm/issues/5371
Follow up: https://github.com/giantswarm/release-operator/pull/50
We introduce the new `pkg/project` package in release-operator, which regroup project wide information like git sha, project name, etc.
Architect now needs to update the git sha, in the `pkg/project` package instead of `main`.
> set git commit SHA in pkg/project.gitSHA

- cmd/deploy.go
- events/events.go
This should allow me to do: `architect deploy --group=testing` in CI, to conditionally deploy to only our testing environments.
> Add a way to create deployment events for only a specific group of testing environments.

- events/events.go
Now we have e2e in place we should install app-operator in control plane clusters so we can start integration testing.
> Add app-operator to the project list

- cmd/build.go
- cmd/deploy.go
- cmd/publish.go
- cmd/root.go
- cmd/unpublish.go
- workflow/workflow.go
Towards: [giantswarm/giantswarm#5206](https://github.com/giantswarm/giantswarm/issues/5206)
Towards: https://github.com/giantswarm/giantswarm/issues/5371
From [voo spec](https://github.com/giantswarm/giantswarm/blob/master/specs/versioning-of-operators.md#ci):
> - Version tag is injected into the "version" variable in package "./pkg/project" during build time.
>     - When the tag is not set for the commit the variable is set to the latest tag in the branch with "+git" suffix. E.g. "v1.2.0+git".
This PR adds version detection to architect.
> add version

- release/release.go
- release/task.go
- workflow/github.go
Towards: giantswarm/giantswarm#5206
Drop `releaseInfo` here in favor of `ReleaseGithubTask`.
> drop releaseInfo

- workflow/github.go
- workflow/pack.go
- workflow/workflow.go
Towards: giantswarm/giantswarm#5206
Add the github release workflow:
- template charts
- package charts (yes there is mutliple chart support now)
- create github release
> add release workflow

- cmd/release.go
- cmd/release/command.go
- cmd/release/error.go
- cmd/release/runner.go
- cmd/root.go
Provide `architect release` command, whenever a git tag is present, it creates a draft github release, with helm charts uploaded as assets.
> add release command

- cmd/root.go
Fixes an issue where `tag` and `version` where not correctly propagated in the `cmd` package.
> fix tag and version propagation

- cmd/release/flag.go
Forgot to add `cmd/release/flag.go` in previous PR.
> forgot the cmd/release/flag.go file

- cmd/root.go
In order to not introduce breaking changes, architect need to be able to continue building charts using the old `1.0.0-<sha>` version. Otherwise draughtman will break see https://github.com/giantswarm/azure-operator/pull/499#issuecomment-479013968.
Also remove the `v` prefix from the version being detected as helm charts do not support this. Additionally docker images tag are preferred to be without this prefix.
> support legacy version, trim v prefix

- cmd/root.go
Towards: https://github.com/giantswarm/azure-operator/pull/499
Fixes an issue where `architect` is building tagged version even if CircleCI is requesting to build regular commit sha.
See https://circleci.com/gh/giantswarm/azure-operator/5229
> only build tag on circleci when explicitly requested

- cmd/circleci/command.go
- cmd/circleci/triggerjob/command.go
- cmd/circleci/triggerjob/error.go
- cmd/circleci/triggerjob/flag.go
- cmd/circleci/triggerjob/runner.go
- cmd/root.go
Towards: https://github.com/giantswarm/giantswarm/issues/5995
This PR set the structure for the new `architect circleci trigger-job` command.
> circleci trigger-job: command structure

- workflow/repo.go
Here we propose dropping the copyright format check. I thought about checking a more lose pattern but then thought that this will also only work as long as everything is up to date or someone writes `copyright` differently. I would like to not have to deal with this as long as there is no real legal need. Checking for the LICENSE file existing at all is good and maybe just good enough.
> drop copyright format check to make forks work

- cmd/helm/command.go
- cmd/helm/template/command.go
- cmd/helm/template/runner.go
- cmd/root.go
Towards: https://github.com/giantswarm/giantswarm/issues/6025
Add structure for the new `architect helm template` upcoming command.
> helm template command structure

- cmd/build.go
- cmd/deploy.go
- cmd/helm/template/command.go
- cmd/hook/error.go
- cmd/hook/preRunE.go
- cmd/publish.go
- cmd/release/command.go
- cmd/root.go
- cmd/unpublish.go
Towards: giantswarm/giantswarm#6025
This PR fixes a bug, where `architect version` and `architect --help` cannot be run outside a git repository and yiel errors (see https://circleci.com/gh/giantswarm/architect/870):
```
2019/05/31 12:40:16 could not get git sha: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc00000ad40), Stderr:[]uint8{0x66, 0x61, 0x74, 0x61, 0x6c, 0x3a, 0x20, 0x6e, 0x6f, 0x74, 0x20, 0x61, 0x20, 0x67, 0x69, 0x74, 0x20, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x20, 0x28, 0x6f, 0x72, 0x20, 0x61, 0x6e, 0x79, 0x20, 0x6f, 0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x20, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x29, 0x3a, 0x20, 0x2e, 0x67, 0x69, 0x74, 0xa}}
```
This is actually required in order to …
> split git related arguments into PreRun hook

- .circleci/config.yml
Towards: giantswarm/giantswarm#6025
This PR call `architect deploy` when building the master branch, this is needed in order to have `quay.io/giantswarm/architect:latest` docker image available.
> tag and push docker latest image

- cmd/deploy.go
- cmd/root.go
Fix an issue where build fail due to empty `sha` variable.
https://circleci.com/gh/giantswarm/giantswarmio-webapp/648
This was introduced in a previous change https://github.com/giantswarm/architect/pull/311
The logic to get sha, tag, branch and version was moved to a different package. We therefore cannot set those values in the `cmd` package.
The way to go now is to use the `cmd.Flag("sha").Value.String()` to retrieve flag values.
> removed unused variables

- Dockerfile
Towards: https://github.com/giantswarm/giantswarm/issues/6025
Add `bash` to the docker image. This makes our life easier with shell scripts.
> add bash to docker image

- workflow/workflow.go
Towards https://github.com/giantswarm/giantswarm/issues/6154.
They are skipped now instead.
> workflow: don't fail for helm subdirectories w/o -chart suffix

- cmd/build.go
- cmd/version.go
- pkg/project/project.go
- workflow/docker_test.go
- workflow/golang.go
- workflow/golang_test.go
- workflow/workflow.go
Towards: https://github.com/giantswarm/giantswarm/issues/6025
This PR fixes an issue where `architect version` yield `version information not compiled`.
```
$ docker run --rm --name architect quay.io/giantswarm/architect version
version information not compiled
```
So now on every golang project being build we inject the build timestamp in `pkg/project.buildTimestamp`.
> inject pkg/project.buildTimestamp on golang build

- template/helm.go
- template/helm_test.go
While configuring CircleCI configuration for packaging and pushing EFK chart to incubator app catalog (see https://github.com/giantswarm/kubernetes-elastic-stack/pull/53) it was discovered that current `architect helm template` command logic assumes all Helm chart files are text files and are treated as template source. EFK chart as it currently stands is a bill-of-materials chart packaging multiple other chart dependencies, provided as tarball packages. Running `architect helm template` for EFK chart panics when trying to template these archives (see https://circleci.com/gh/giantswarm/kubernetes-elastic-stack/4).
This PR supports skipping templating of *.tgz files.
> Skip templating tgz files

- events/events.go
This reverts commit ee946e6eb575652e4e5d7d58be547baaf5ab5436.
Because ginger is a testing environment again for a while now.
> Revert "Remove ginger from the testing group. (#297)"

- template/helm.go
This PR fixes error handling in helm templating walk. It also handles case when walk is called with non-nil error passed in.
Bug was uncovered by @pipo02mix when trying to `architect helm template` https://github.com/giantswarm/prometheus-operator-app/tree/master/helm/kubernetes-prometheus-chart 
See related discussion on slack: https://gigantic.slack.com/archives/C3C7ZQXC1/p1562842254031900
> Fix error handling in helm templating walk

- template/helm.go
This PR makes `architect helm template` tgz check nil safe.
I've tested it on https://github.com/giantswarm/prometheus-operator-app/tree/master/helm/kubernetes-prometheus-chart - before PR `architect helm template` would segfault, and after it completes successfully.
```
$ architect helm template --dir ./helm/prometheus-operator-app-chart
2019/07/12 00:03:17 templating helm chart
dir: ./helm/prometheus-operator-app-chart
sha: e877bd37b17d9b7e75d762ec61ac2a3d73220962
tag: 0.1.0
version: 0.1.0
2019/07/12 00:03:17 templated helm chart
```
> Make helm template tgz check nil safe

- cmd/project/command.go
- cmd/project/version/command.go
- cmd/project/version/runner.go
- cmd/root.go
Towards: https://github.com/giantswarm/giantswarm/issues/6557
This PR provides a new command: `architect project version` which just output the version being discovered by architect when building a project. So we can re-use this from other scripts like circleci orbs.
> new command: architect project version

- template/helm.go
- template/helm_test.go
- template/template.go
- workflow/helm.go
Towards: https://github.com/giantswarm/giantswarm/issues/6557
This is too confusing to have `.DockerTag` and `.Version` when templating helm charts, so we decided to only have `.Version` which we use to tag the docker image and the chart. So everything get the same version tag.
Simplicity is beauty 🌟 
⚠️ Do not merge before `.DockerTag` is removed from aws-operator and azure-operator helm charts.
> remove support for .DockerTag in helm template

- cmd/build.go
- tasks/docker_test.go
Upgrading from Go 1.11.x to 1.12.x brought up issues with
`prometheus-config-controller` tests and this was a good catch. Therefore
upgrading latest compiler to be the default in CI as well is a good thing.
Required retagged image PR is here: https://github.com/giantswarm/retagger/pull/243
> Use latest Go (1.12.9)

- cmd/build.go
- tasks/docker_test.go
Default to 1.13, aligned with Go version in https://github.com/giantswarm/architect/blob/master/Dockerfile#L2
> Use Go 1.13

- cmd/hook/preRunE.go
Towards: https://github.com/giantswarm/giantswarm/issues/7044
We no longer want to set default version to `1.0.0` but instead use `0.0.0`.
NOTE: tag aws-operator with v1.0.0 before merging this.
> set default version to 0.0.0 instead of 1.0.0

- events/events.go
Reverts giantswarm/architect#355
Towards https://github.com/giantswarm/giantswarm/issues/8207
Operator week hackathon operators destabilized test installations - removing operator-week-app-collection while it's still easy.
> Revert "add operator-week-app-collection"

- Dockerfile
This commit adds Helm Chart testing tool
(https://github.com/helm/chart-testing). Rather than copy what is in the
Dockerfile of that repo, simply use the image and copy aritfacts from it. This
ensures we have exactly the same versions as used in upstream Image.
Will go towards https://github.com/giantswarm/architect-orb/pull/65
> Add Helm chart testing tool

- workflow/helm.go
- workflow/workflow.go
- workflow/workflow_test.go
This was a feature used to push the helm chart to the registry while working on operators branches. That made possible to deploy the operator chart to run e2e tests.
We need to find a way to make the apiextensions repository to push the helm charts using sha instead of always overwritting `0.1.0`.
> Revert #359

- workflow/golang.go
- workflow/golang_test.go
Towards https://github.com/giantswarm/giantswarm/issues/8637
We want to invert how the project version is maintained and instead of
generating it from git data and injecting during the build, we want to
maintain it in source files. This will allow managing releases by
merging PRs and that they'll undergo a review process.
> cmd, workflow: stop injecting version into build info

- Dockerfile
Rather than setting up remote docker and pulling a separate image on every scan, add the linting tool directly to the architect image and use in-place. Supports https://github.com/giantswarm/architect-orb/pull/87
Toward https://github.com/giantswarm/giantswarm/issues/8901 https://github.com/giantswarm/giantswarm/issues/7658
> Add binary install of golangci-lint to architect image

- cmd/helm/template/runner.go
- helmtemplate/helm.go
- helmtemplate/helm_test.go
- helmtemplate/types.go
Towards https://github.com/giantswarm/giantswarm/issues/8632
Add Git branch name to context data used when templating Helm charts.
It's already available as a flag but previously wasn't exposed to the
template. We now want to include it to be able to expose it via a label
on the resources created by the template.
> helmtemplate: Add branch name to template context

- Dockerfile
Installing conftest would allow us to check our kubernetes manifests / helm charts using OPA policies.
PoC
When changing `Deployment` api version
> Install conftest and policies

- Dockerfile
- cmd/build.go
- go.mod
- tasks/docker_test.go
There are quite a few significant changes [in 1.14](https://blog.golang.org/go1.14) including performance improvements, and I think it's best if we don't get too far behind on our versions. We use the latest release of `architect` in many places so we'll need to do some testing before actually merging this PR. I just wanted to get the conversation started about whether/when we should upgrade.
Build error should be fixed once https://github.com/giantswarm/retagger/pull/384 is merged.
> Update to golang 1.14.1

- events/events.go
Toward https://github.com/giantswarm/giantswarm/issues/7895
Removing app-operator from draughtsman.
> Removing app-operator from deployment

- events/events.go
After https://github.com/giantswarm/giantswarm/issues/9339 cert-operator
will be pushed to _aws_, _kvm_ and _azure_ app catalogs. This makes its
`baseProjectList` entry obsolete.
> remove cert-operator from baseProjectList

- CHANGELOG.md
- go.mod
- go.sum
Towards https://github.com/giantswarm/giantswarm/issues/10272.
This is the version released after migrating to go modules, which makes
the `go.mod`, etc. tidier.
> Update giantswarm/app to 0.2.1

- cmd/helm/template/runner.go
AppVersion value in Chart.yaml will not be rendered for repositories which do not have pkg/project/project.go. Let's assign Version value to AppVersion in this case.
Fixes https://github.com/giantswarm/giantswarm/issues/10270
> Ensure AppVersion for repos without pkg/project

- cmd/helm/template/runner.go
- helmtemplate/helm.go
Managed apps do not have any go project files and the AppVersion in this
case refers to the version deployed by Helm. Not linked to any particular
project.
If project.go is not present or when checking for appVersion
in the project files returns an empty string then skip the validation checks.
Slack thread related to this commit:
https://gigantic.slack.com/archives/CRZN9GLJW/p1588605374410900
> Skip AppVersion check when project file is absent

- Dockerfile
Helm in architect should be upgraded to 3.2.4 to recognize helm 3 functions. (e.g. `lookup`)
> Upgrade helm to 3.2.4

- CHANGELOG.md
- cmd/preparerelease/internal/funcs.go
- cmd/preparerelease/internal/key.go
- cmd/preparerelease/internal/modifier.go
- cmd/preparerelease/runner.go
If go.mod file exists and version is bigger than v1 it will add a proper `/vN` suffix to module line:
E.g.:
```diff
- module github.com/giantswarm/architect
+ module github.com/giantswarm/architect/v2
```
> Update go.mod when preparing release

- CHANGELOG.md
- cmd/preparerelease/internal/modifier.go
So we have these kinds of releases like `0.1.0-1` which are used to replace respective release version (e.g. `0.1.0` in this case). 
1. `architect prepare-release` fails to parse flag value when you use such version.
2. if such version is used, `project.go` should not be changed as otherwise e.g. operator is not able to reconcile CRs as it uses wrong version
This PR fixes those cases.
> Handle fix releases like 0.1.0-2

- CHANGELOG.md
- Dockerfile
- go.mod
- tasks/docker_test.go
[Go 1.15 was released last month](https://golang.org/doc/devel/release.html#go1.15). It would be good to be up to date on this. The new go docker image [has been added to rettager](https://github.com/giantswarm/retagger/pull/485).
> Update to Golang 1.15.2

- CHANGELOG.md
- cmd/preparerelease/internal/modifier.go
We tried to release v5.0.0-alpha2 after having v5.0.0-alpha1 out.
The release automation broke because it didn't find the following line:
```
[Unreleased]: https://github.com/giantswarm/azure-operator/compare/v5.0.0-alpha1...HEAD
```
This PR fixes this problem
> Accept alphanumeric strings for release suffix 

- .github/workflows/zz_generated.create_release.yaml
- .github/workflows/zz_generated.create_release_pr.yaml
- .github/workflows/zz_generated.gitleaks.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/14557
This PR resulted from : `devctl gen workflows --flavour cli`
Fixes the following errors in github actions
```
Error: Unable to process command '::add-path::/opt/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
> update github workflows

- CHANGELOG.md
- Dockerfile
This allows running integration tests based on controller-runtime
[envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest).
> Add kubebuilder to the image

- Dockerfile
This PR changes the container image to copy the chart schema from app-build-suite.
Background:
For the app metadata story https://github.com/giantswarm/giantswarm/issues/10926 we've added some additional keys to `Chart.yaml` files of some components. (like `restrictions`, `compatibleProviders`). While `app-build-suite` makes `ct lint` aware of these new keys, standard chart testing does not know about the new keys schemas and makes CI runs fail for projects not using `app-build-suite` for packaging helm charts.
Check https://app.circleci.com/pipelines/github/giantswarm/chart-operator/1684/workflows/b300b87f-c7e5-40d7-a3c7-219fc57a31a3/jobs/16000 for reference failing CI run.
Fixed CI run using architect from this branch https://app.circleci.com/pipelines/github/giantswarm/chart-operator/16 …
> Copy chart schema from app-build-suite

- go.mod
- go.sum
fixes https://app.circleci.com/pipelines/github/giantswarm/architect/952/workflows/6c4273a5-93af-42e1-8312-2f40d14eaa48/jobs/2646/parallel-runs/0/steps/0-117
> pin jwt-go lib to avoid CVE-2020-26160

- Dockerfile
The previously used URL stopped working, despite still being mentioned in the package documentation.
```
curl: (22) The requested URL returned error: 404
```
[Example of a job failed with the error](https://app.circleci.com/pipelines/github/giantswarm/architect/1174/workflows/cb3d4010-c3d5-424f-9843-d215e9ca9451/jobs/3067)
> Change kubebuilder download URL

- CHANGELOG.md
- Dockerfile
Towards: giantswarm/giantswarm#18975
Adding [`kubeval`](https://www.kubeval.com/) in order to be able to detect duplicate resources in charts.
e.g.
```
$ helm template test ./helm/prometheus-rules --namespace monitoring --values ./helm/prometheus-rules/ci/default-values.yaml --is-upgrade|./kubeval --ignore-missing-schemas -
WARN - Set to ignore missing schemas
ERR  - prometheus-rules/templates/recording-rules/service-levels.rules.yml: Duplicate 'PrometheusRule' resource 'service-level.rules' in namespace 'monitoring'
```
> add kubeval

- CHANGELOG.md
- cmd/preparerelease/flag.go
- cmd/preparerelease/runner.go
Needed for https://github.com/giantswarm/devctl/pull/332
See https://github.com/giantswarm/actions-test/pull/46 for example
The new automation will automatically generate release notes based on commits since the last release. As a result, we can stop editing `CHANGELOG.md` for repositories using this method. This PR makes architect not attempt to update `CHANGELOG.md`. It defaults to false so shouldn't affect any existing users.
> Add update-changelog flag to prepare-release

- cmd/create/kustomization/runner.go
- cmd/create/kustomization/runner_test.go
- cmd/create/kustomization/testdata/expected/kustomization.yaml_0
- cmd/create/kustomization/testdata/expected/kustomization.yaml_1
- cmd/create/kustomization/testdata/expected/kustomization.yaml_2
- cmd/create/kustomization/testdata/expected/kustomization.yaml_3
- cmd/create/kustomization/testdata/input/flux-manifests_1/kustomization.yaml
- cmd/create/kustomization/testdata/input/flux-manifests_2/kustomization.yaml
- cmd/create/kustomization/testdata/input/flux-manifests_4/kustomization.yaml
This is a result of [this](https://gigantic.slack.com/archives/C02GDJJ68Q1/p1664151357042399) conversation.
In general, to populate App CRs generated with `konfigure` I could update the `konfigure` itself, but on the other hand, since we use `kustomization.yaml` to pass input to `konfigure`, we may as well use it to further customize the App CRs, without falling to update `konfigure` each time.
Yet, currently it is not possible becaue `architect` override the `kustomization.yaml` each time, for example see https://github.com/giantswarm/aws-app-collection/commit/0a3e762e330d1465fa2fbe6564ff40bc96effebb.
This PR changed this behaviour.
> Do not override everything in the `kustomization.yaml`

- CHANGELOG.md
- Dockerfile
Towards https://github.com/giantswarm/giantswarm/issues/23916
Also:
- Update Go to 1.19.1.
- Update Alpine to 3.16.2 (used by Go 1.19.1 image).
- Update Go CI linter to 1.49.0 (to get latest linter with the latest go).
> Update Go to 1.19.1

- .nancy-ignore
- CHANGELOG.md
- Dockerfile
Blocked by https://github.com/giantswarm/retagger/pull/856
> Bump Go to v1.20.6

- CHANGELOG.md
- Dockerfile
Go tools must be upgraded together so they work with Go 1.21, and yamllint also failed with the latest Alpine so I bumped it too
> Update Go to v1.21.3, golangci-lint to v1.55.2, nancy to v1.0.45, yamllint to v1.32.0

- Dockerfile
Towards:
- https://github.com/giantswarm/giantswarm/issues/31374
- https://github.com/giantswarm/giantswarm/issues/31396
Bump `golang:1.21.12-alpine3.19` to fix following critical CVEs:
- CVE-2024-24790
> Bump golang:1.21.12-alpine3.19

- Dockerfile
- renovate.json5
This should let Renovate update the dependency versions set via ARG directives.
> Allow renovate to update dependencies in Dockerfile

- .circleci/config.yml
The goal of this PR is to make architect run on ARM, so that it can be used in CircleCI ARM Docker runners.
> Add building for arm64

- Dockerfile
Follow-up to https://github.com/giantswarm/architect/pull/1212
Previously the binary included in the arm64 architecture part of the image was not suited for arm.
This PR aims to build an image where the binary is actually an ARM one.
Test:
> Fix multi-arch image for arm64
