circle.yml, cmd/deploy.go, cmd/version.go
- Fixes missing server argument
- Add a version command
=> General late night improvements

cmd/deploy.go
Towards https://github.com/giantswarm/architect/issues/23
Reverts giantswarm/architect#22
=> Revert "Removes docker email from docker login"

README.md
Towards https://github.com/giantswarm/architect/issues/24
=> Improves readme a little

commands/commands.go, commands/commands_test.go, workflow/workflow.go, workflow/workflow_test.go
=> Improves workflow printing

cmd/deploy.go, utils/kubernetes.go, workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1300
=> Adds support for deploying to multiple clusters

workflow/certs.go, workflow/clusters.go, workflow/docker.go, workflow/golang.go, workflow/kubectl.go, workflow/workflow.go
trying to make `workflow.go` a little less awful
=> Refactors workflow package

cmd/build.go
Towards https://github.com/giantswarm/giantswarm/issues/1368
=> Updates golang to 1.8.1

workflow/golang.go, workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1302
=> Adds go fmt and go vet

workflow/golang.go
Towards https://github.com/giantswarm/architect/issues/20
=> Adds commit as ldflag

configuration/provider/aws/aws.go, configuration/provider/aws/ec2/ec2.go, configuration/provider/aws/ec2/instance/instance.go, configuration/provider/provider.go, installation/aws.go
Towards https://github.com/giantswarm/api/issues/350.
=> added draft for instance type configuration

template/filters.go, template/filters_test.go
Towards https://github.com/giantswarm/api/issues/350. We need a filter to make a string out of a list because we do not want to hustle with for loops in our templates for now. This might change in the future, but lets do baby steps here.
=> added listToString filter

configuration/provider/aws/ec2/instance/instance.go, configuration/provider/aws/ec2/instance/instance_test.go, template/filters.go
This PR fixes the cause of the cluster-service build failure. See https://circleci.com/gh/giantswarm/cluster-service/263. See also https://github.com/giantswarm/cluster-service/pull/116.
=> fix type issue of custom filter

configuration/provider/aws/ec2/instance/instance.go, installation/aws.go, template/filters.go
Towards https://github.com/giantswarm/cluster-service/pull/119.
=> added configuration for capabilities

workflow/docker.go
=> Fixes missing docker email for older docker versions

workflow/workflow.go, workflow/workflow_test.go
Fixes https://github.com/giantswarm/architect/issues/48
=> Replaces hardcoded kubernetes directory string with configured path

workflow/clusters.go, workflow/clusters_test.go, workflow/kubectl.go
We're gonna remove this soonish, but it's been bugging me :D
=> Changes to use autobuilt kubectl image

commands/commands.go, commands/commands_test.go, workflow/golang.go
Sorry, didn't actually test that it would be a valid docker command.
This should fix it
=> Fix network flag

commands/commands.go, commands/commands_test.go, workflow/golang.go
This reverts commit 2563269b35f90733fe20da77e142a36695691352.
=> Revert "Network host (#78)"

configuration/guest/kubectl/kubectl.go
Closes #89 and https://github.com/giantswarm/giantswarm/issues/1478.
Not sure what the best way to test this before deploying it is.
=> Update deployed kubectl to 1.6.4

workflow/docker.go, workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1499
=> Adds support for tagging and pushing latest

configuration/provider/kvm/flannel/flannel.go, configuration/provider/kvm/kvm.go, configuration/provider/provider.go, installation/leaseweb.go
Towards https://github.com/giantswarm/giantswarm/issues/1526
=> configure VNI range for KVM

configuration/provider/kvm/ingress/ingress.go, configuration/provider/kvm/kvm.go, installation/leaseweb.go
Towards https://github.com/giantswarm/giantswarm/issues/1526.
=> added port range for KVM Leaseweb

events/events.go
We need this apparently for a new installation. So just getting it out here.
=> added vikings environment

configuration/provider/kvm/dns/dns.go, configuration/provider/kvm/kvm.go, installation/leaseweb.go, template/filters.go
Towards https://github.com/giantswarm/k8s-network-bridge/issues/16.
=> added DNS servers

configuration/provider/kvm/kvm.go, configuration/provider/kvm/ntp/ntp.go, installation/leaseweb.go
For use in kubernetesd configmap
=> Add NTP servers to KVM provider

template/error.go, template/kubernetes.go, template/kubernetes_test.go, template/template.go, workflow/error.go, workflow/kubectl.go, workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/architect/issues/73
=> Refactors kubernetes resource templating to task interface

workflow/golang.go
Fixes https://github.com/giantswarm/architect/issues/124
Friday afternoon boy scouting
See https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwie0M6Wi4nVAhViBsAKHcXcDJIQFggoMAA&url=https%3A%2F%2Fblog.golang.org%2Frace-detector&usg=AFQjCNHDL5dteYLrdLeDB8sFRA542qR2HA
=> Adds race detector to golang test task

events/events.go
make sure architect adds the deployment events for heisenberg.
=> add heisenberg installation

events/events.go
I want to deploy `etcd-backup` to Centaur in a proper way.
All following PR are related to this:
https://github.com/giantswarm/architect/pull/134
https://github.com/giantswarm/etcd-backup/pull/9
https://github.com/giantswarm/installations/pull/39
=> Add etcd-backup to Centaur

events/events.go
=> add anubis

events/events.go
This is new GiantSwarm environment
that will be used for customer playgrounds
=> Add ginger

workflow/golang.go, workflow/helm.go, workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1785
=> Adds retry pull tasks for golang and helm

cmd/build.go, cmd/deploy.go, cmd/root.go, workflow/docker.go, workflow/docker_test.go, workflow/workflow.go
Fixes https://github.com/giantswarm/giantswarm/issues/1605.
=> Branch name

workflow/workflow.go, workflow/workflow_test.go
Fixes https://github.com/giantswarm/giantswarm/issues/1606.
=> push images on build

events/events.go
related to: https://github.com/giantswarm/installations/pull/78
related to: https://github.com/giantswarm/giantswarm/issues/1813
=> Add events for our frontend guest cluster ginger_vxvc7

events/events.go
Related changes
https://github.com/giantswarm/installations/pull/117
https://github.com/giantswarm/calico-node-controller/pull/5
=> Add calico node controller to gauss

events/events.go
Related change https://github.com/giantswarm/installations/pull/119
=> Add calico-node-controller to all AWS

events/events.go
add architect event for `jackal`
=> add-jackal-events

events/events.go
adding events for new aws cluster
=> add-avatar-events

events/events.go
azure-operator will be added as soon as it will be build.
=> Adds gollum

events/events.go
azure-operator already deployed in `gollum` via Helm.
=> Adds azure-operator to gollum

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/2093
=> Add cert-exporter to project lists

Gopkg.lock, cmd/publish.go, pipeline/error.go, pipeline/pipeline.go, pipeline/pipeline_test.go, pipeline/spec.go, vendor/gopkg.in/yaml.v2/.travis.yml, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/NOTICE, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/go.mod, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go
Towards https://github.com/giantswarm/giantswarm/issues/1902
Determines initial the name off the initial channel in the pipeline from the chart version.
=> Determine start pipeline channel

cmd/build.go
Reverts giantswarm/architect#187
=> Revert "Update golang-version default to 1.10.0"

cmd/build.go
Reverts giantswarm/architect#198. Waiting for https://circleci.com/gh/giantswarm/retagger/165 to finish.
=> Revert "Revert "Update golang-version default to 1.10.0""

workflow/golang.go, workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/aws-operator/issues/837.
=> uses caching for golang artifacts

events/events.go
=> add-godsmack

events/events.go
cleaning up after giantswarm/giantswarm#2146
=> removed old front end cluster

cmd/publish.go
Towards https://github.com/giantswarm/giantswarm/issues/1902.
Make that publish command actually work.
=> Fix publish command

workflow/workflow.go, workflow/workflow_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1902
=> Add missing Helm login task to publish workflow

cmd/publish.go, pipeline/pipeline.go, pipeline/pipeline_test.go, pipeline/spec.go
Towards https://github.com/giantswarm/giantswarm/issues/1902
Allows publishing to stable channels.
=> publish to stable channel

events/events.go
New Azure environment for deutsche telekom
=> Add taranatula

cmd/build.go
See https://github.com/giantswarm/retagger/issues/96 for retagging.
=> Upgrades golang to 1.10.3

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/3686
=> Remove 6f342 from architect

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/3313
=> Deploy release-operator to all installations

events/events.go
For https://github.com/giantswarm/giantswarm/issues/4219#event-1862934136
=> Remove desmotes from deployment events

events/events.go
temporary solution for https://github.com/giantswarm/giantswarm/issues/4282
=> remove-route53-from-girafe

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/4313
=> Removes cloudwatch exporter from aws test environments

workflow/helm.go
Towards https://github.com/giantswarm/giantswarm/issues/4938
=> Upgrade docker-helm image to Helm 2.12.0

events/events.go
related: https://github.com/giantswarm/giantswarm/issues/3952
=> Remove ingress-operator from projects list

events/events.go
Add auto-oncall app into production server
=> Add auto-oncall application

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/4779
=> Adds kpi-prometheus repo to frontend cluster project list

workflow/docker_test.go, workflow/golang.go, workflow/golang_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/5371
Inject the version being built into the go binary at `pkg/project.version`
Also provide test for `NewGoBuildTask`.
=> Inject version into go binary

pack/pack.go, pack/pack_test.go
Add unit test for helm package task (`PackageHelmChartTask`).
1. create a chart
2. package the chart
3. check that the created helm chart archive contains what we expect
=> add test for PackageHelmChartTask

cmd/release/runner.go
I forgot to pass the login details to the projectInfo struct.
=> pass helm login info into projectInfo

events/events.go
Since it is becoming a prod env for now.
=> Remove ginger from the testing group.

events/events.go
=> add github-exporter to project list

events/events.go
=> add-gorilla

events/events.go
- Adding `circleci-exporter` into the `gollum` installation.
=> Adding circleci-exporter

events/events.go
add ingress-exporter to kvm project list
for https://github.com/giantswarm/giantswarm/issues/5199
=> add-ingress-exporter

cmd/helm/template/flag.go, cmd/helm/template/runner.go
Towards: giantswarm/giantswarm#6025
Add the logic for architect helm template command.
It's sole purpose is to template helm chart.
=> helm template, command logic

Dockerfile
Towards: https://github.com/giantswarm/giantswarm/issues/6025
Create a docker image for architect to be used from circleci.
This docker image contains architect + other tools we need.
Tools required from our side:
* architect
* git
* helm
=> container for architect

Dockerfile, events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/5980.
=> add new bridge-operator to KVM

workflow/docker.go, workflow/golang.go
Would be cool if we could be a bit more disciplined. `architect` is pretty messy.
=> order methods alphabetically

events/events.go
add new kvm environment to the list
=> add-buffalo

template/helm.go
This reverts commit e8a2207a087142b2ebdc00723e281f40d09083d8.
=> Revert "Fix error handling in helm templating walk (#322)"

Dockerfile
Towards: giantswarm/giantswarm#6557
=> Provides docker in architect docker image

template/helm.go
Towards https://github.com/giantswarm/giantswarm/issues/6557
See https://github.com/giantswarm/aws-operator/pull/1804/files#diff-39f31ed2a4f9740e98c9adb74ad80904R12.
=> template: add replace template function

template/helm.go
Towards https://github.com/giantswarm/giantswarm/issues/6557
See https://github.com/giantswarm/aws-operator/pull/1815
=> template: remove replace function from templates

Dockerfile
- Install go 1.13.0
- Update to alpine 3.10
- Use rettaged images
- Keep curl
- Remove versions from installed binaries
=> dockerfile: install go 1.13.0

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/7480
=> circleci: update architect orb to 0.4.4

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/7349
Removing some apps as we no longer deploy them via draughtsman.
=> Removing some apps from gollum_6iec4

events/events.go
=> Fixes comment

cmd/helm/template/runner.go, helmtemplate/error.go, helmtemplate/helm.go, helmtemplate/helm_test.go, helmtemplate/template.go, helmtemplate/types.go
Fixes giantswarm/giantswarm#7614
=> helm-chart-template: template only the values.yaml and Chart.yaml files

go.mod, go.sum
Towards https://github.com/giantswarm/giantswarm/issues/7888
=> go.mod: update gitrepo

events/events.go
gk software production installation 
see: https://github.com/giantswarm/giantswarm/issues/7902
=> Added goku

events/events.go
Towards: https://github.com/giantswarm/giantswarm/issues/7509
Adding the app-collection for operator week to architect.
=> add operator-week-app-collection

events/events.go
Adde new dvag installation called "davis"
=> Added davis installation

events/events.go
Add PMI installation 'platypus'
=> Add platypus environment

events/events.go
Added icarus installation (a few weeks late)
=> Added icarus

cmd/helm/template/runner.go, cmd/helm/template/runner_test.go, cmd/hook/pre_run_e.go, go.mod, go.sum
Towards: https://github.com/giantswarm/giantswarm/issues/8632
Read the version stored in the project's source code at `pkg/project/project.go`.
=> Retrieves version from project.go file

cmd/helm/template/flag.go, cmd/helm/template/runner.go, go.mod, helmtemplate/error.go, helmtemplate/helm.go, helmtemplate/helm_test.go, helmtemplate/types.go
Towards: giantswarm/giantswarm#8632
Adds version from `project.go` as `AppVersion` value for the chart.
=> Provide .AppVersion as Chart.yaml value

helmtemplate/error.go, helmtemplate/helm.go
Towards: giantswarm/giantswarm#8632
Follow-up to https://github.com/giantswarm/architect/pull/371
=> Fix condition which triggers error on failed validateChart

helmtemplate/error.go, helmtemplate/helm.go
Towards: giantswarm/giantswarm#8632
Adding a specific error with handler in case of validation error so it's easier to test those case.
=> return validationFailedError in case of validation failure

go.mod, helmtemplate/helm_test.go, helmtemplate/testdata/test0/Chart.yaml, helmtemplate/testdata/test0/values.yaml, helmtemplate/testdata/test1/Chart.yaml, helmtemplate/testdata/test1/values.yaml
Towards: giantswarm/giantswarm#8632
* Refactor test to use golden files/folder.
* Add more test cases for validation
=> Refactor test for TemplateHelmChartTask

cmd/helm/template/flag.go, cmd/helm/template/runner.go, helmtemplate/helm.go
Towards https://github.com/giantswarm/giantswarm/issues/8635
I realised there are "branch" builds and "tag" builds and this makes so
much more sense in my head.
=> template: rename --tagged-build to --tag-build

helmtemplate/helm.go
Towards https://github.com/giantswarm/giantswarm/issues/8635
=> helmtemplate: improve validation error messages

helmtemplate/helm.go
Towards https://github.com/giantswarm/giantswarm/issues/8635
=> helmtemplate: improve version and tag mismatch error message

events/events.go
Towards https://github.com/giantswarm/giantswarm/issues/9219
=> Remove g8s-cert-manager

events/events.go
=> Remove g8s-prometheus

events/events.go
Towards giantswarm/giantswarm#10177
=> Remove g8s-efk from events

events/events.go
=> Remove g8s-grafana

events/events.go
=> Remove bridge-operator chart

events/events.go
=> Remove flannel-operator

events/events.go
=> Remove node-operator

events/events.go
=> Remove cluster-service

events/events.go
=> Delete userd 

events/events.go
=> Delete tokend from architect

events/events.go
=> Add antelope env

events/events.go
=> Add argali env

events/events.go
=> Remove companyd

events/events.go
=> events: remove net-exporter from the project list

events/events.go
=> Remove ingress-exporter from base project list

events/events.go
=> events: remove etcd-backup

events/events.go
Towards giantswarm/giantswarm#10177
=> Remove cert-exporter from baseProjectList

events/events.go
=> events: remove vault-exporter

events/events.go
Towards giantswarm/giantswarm#10177
=> Remove route53-manager

events/events.go
=> Remove passage from project list

events/events.go
=> Remove credentiald from project list

events/events.go
=> Remove api from project list

events/events.go
=> Remove happa

CHANGELOG.md, pkg/project/project.go
Towards: https://github.com/giantswarm/giantswarm/issues/10897
=> Prepare release for 1.1.0

events/events.go
Towards: giantswarm/giantswarm#11536
=> Removed impala

CHANGELOG.md, cmd/preparerelease/internal/modifier.go
To fix issues like this one https://github.com/giantswarm/cluster-operator/pull/1140
=> Support fresh non-master changelog

CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/12241
=> Add note about camel to changelog

.github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml
With:
```
devctl gen workflows --flavour cli
```
=> Generate workflows

Makefile
Towards https://github.com/giantswarm/giantswarm/issues/12241
=> Update generated Makefile

events/events.go
This PR adds the new `visitor` installation to architect
=> Added visitor

events/events.go
remove camel - installation test is finished for now
remove centaur- it's gone for long time already
=> remove camel and centaur

CHANGELOG.md, helmtemplate/helm.go, pkg/project/project.go
Another place where we need to skip reference version validation
=> Ignore reference versions in helm template validation

CHANGELOG.md, cmd/preparerelease/internal/modifier.go, cmd/preparerelease/internal/modifier_test.go
Towards https://github.com/giantswarm/giantswarm/pull/12732
=> Remove suffix from reference version in project.go

CHANGELOG.md, Dockerfile
Towards https://github.com/giantswarm/giantswarm/issues/8901
Adds the `nancy` binary to the architect image to be used by `architect-orb`
=> Add Nancy to architect image

events/events.go
Added new orange installation `orion`
=> Added orion

CHANGELOG.md
=> added changelog entry

cmd/create/appcr/command.go
Towards: https://github.com/giantswarm/giantswarm/issues/14557
=> fix user flag

cmd/create/appcr/command.go, cmd/create/appcr/runner.go
Towards https://github.com/giantswarm/giantswarm/issues/14603
I'm preparing for adding `--annotations` flag.
=> Refactor flags setting in `create appcr`

CHANGELOG.md, cmd/create/appcr/command.go, cmd/create/appcr/error.go, cmd/create/appcr/runner.go, cmd/create/appcr/validate.go, cmd/create/appcr/validate_test.go, go.mod, go.sum
Towards https://github.com/giantswarm/giantswarm/issues/14603
Waiting for https://github.com/giantswarm/app/pull/50
=> Add --config-version flag to `create appcr`

CHANGELOG.md
just adding some missing entries to the changelog
=> update changelog with missed entries

.circleci/config.yml
Use go 1.16 to build the architect binary
=> Use architect-orb 2.2.0

.circleci/config.yml, CHANGELOG.md, Dockerfile, cmd/version.go, tasks/docker_test.go
Update go to 1.16.2 and architect-orb to 2.3.0
=> Update go version to 1.16.2

events/events.go
towards https://github.com/giantswarm/giantswarm/issues/16850
=> add eagle to envs

CHANGELOG.md, cmd/create/argoapp/command.go, cmd/create/argoapp/command_test.go, cmd/create/argoapp/error.go, cmd/create/argoapp/runner.go, cmd/create/command.go, go.mod, go.sum
Towards https://github.com/giantswarm/giantswarm/issues/16948
```
$ go run main.go create argoapp -o yaml --name pawel-test --app-version 1.2.3 --app-catalog pawel-catalog --app-name pawel-app --config-ref v2 --app-destination-namespace pawel-ns
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: pawel-test
namespace: argocd
spec:
destination:
namespace: pawel-ns
server: https://kubernetes.default.svc
project: draughtsman2
source:
path: .
plugin:
env:
- name: KONFIGURE_APP_NAME
value: pawel-app
- name: KONFIGURE_APP_VERSION
value: 1.2.3
- name: KONFIGURE_APP_CATALOG
value: pawel-catalog
name: konfigure
repoURL: https://github.com/giantswarm/config.git
targetRevision: v2
syncPolicy:
automated:
prune: true
```
=> Add create argoapp command

CHANGELOG.md, Dockerfile
Will be used to remove `.status` field from App CR in orb
=> Add yq into dockerfile

CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/16948
=> Add missing release note

CHANGELOG.md, go.mod, go.sum
Towards https://github.com/giantswarm/giantswarm/issues/16948
=> Fix project name (collections)

CHANGELOG.md, cmd/create/argoapp/runner.go
Towards https://github.com/giantswarm/giantswarm/issues/17297
=> Don't fail when Chart.yaml doesn't have the config annotation

CHANGELOG.md, go.mod, go.sum
Towards https://github.com/giantswarm/giantswarm/issues/17315
=> Update argoapp to v0.1.2

CHANGELOG.md, events/events.go
towards https://github.com/giantswarm/giantswarm/issues/16680
=> add gopher to installations

go.mod, go.sum
Towards https://github.com/giantswarm/giantswarm/issues/18615
=> update argoapp to v0.1.3

CHANGELOG.md
This PR repairs links in the CHANGELOG.md file to point to the right directory.
=> Fix links in changelog to point to this repository

CHANGELOG.md, Dockerfile
Towards https://github.com/giantswarm/roadmap/issues/391
=> Update helm to v3.8.1

Dockerfile
Towards https://github.com/giantswarm/giantswarm/issues/22048
=> Update Go to 1.18.1

CHANGELOG.md, Dockerfile
Adds `jq` to the docker image.
=> Add jq util

cmd/hook/pre_run_e.go, go.mod, go.sum
Towards: https://github.com/giantswarm/roadmap/issues/3408
Related to: https://github.com/giantswarm/gitrepo/pull/81
=> Bump github.com/giantswarm/gitrepo to e09627c2009bf03a85873fca026dbc384210c0dd

cmd/create/fluxgenerator/runner.go, cmd/create/kustomization/runner.go, cmd/helm/template/runner.go, cmd/preparerelease/internal/modifier.go
Closes https://github.com/giantswarm/giantswarm/issues/32982
=> Adapt code for golangci-lint v2

CHANGELOG.md, Dockerfile, Makefile.gen.go.mk
Towards https://github.com/giantswarm/giantswarm/issues/32927
=> Remove golangci-lint
